local assert = require("luassert")
local api = require("cognite.openai.api")

describe("generateRequest", function()
	it("should return a OpenAIRequest", function()
		local t = require("cognite.openai.types")
		-- local request = api._internal.generateRequest("My question to AI")
		-- assert.is_table(request)
	end)
end)

describe("askAI", function()
	it("should return a OpenAIResponse", function()
		-- local response = api.askAI("My question to AI")
		-- assert.is_string(response)
		-- assert.is_table(response)
	end)
end)

describe("generateMessage (internal)", function()
	it("should return a OpenAIMessage", function()
		local t = require("cognite.openai.types")
		local message = api._internal.generateMessage("user", "My question to AI")
		assert.is_table(message)
		assert.is_string(message.__raw.role)
		assert.is_string(message.__raw.content)
		assert.are.same(message.__raw.role, "user")
		assert.are.same(message.__raw.content, "My question to AI")
	end)
end)
